name: ST-DefaultKit
main: net.starly.defaultkit.DefaultKit
author: Starly Team
website: https://discord.gg/TF8jqSJjCG

description: DefaultKit Plugin

version: 1.0_Alpha
api-version: 1.16

softdepend:
  - ST-Core

commands:
  defaultkit:
    aliases: [dk, 기본템]